# This is sample config file for quorum reporting
title = "Quorum reporting confg example"

[reporting]

	WSUrl = "ws://localhost:23000"
	GraphQLUrl = "http://localhost:8547/graphql"
	Addresses = ["0xed9d02e382b34818e88b88a309c7fe71e65f419d", "0xca843569e3427144cead5e4d5999a3d0ccf92b8e"]
	rpcAddr =  "localhost:6666"
	rpcCorsList =  ["localhost"]
	rpcvHosts = ["localhost"]