# This is sample config file for quorum reporting
title = "Quorum reporting confg example"

[reporting]

	WSUrl = "ws://localhost:23000"
	GraphQLUrl = "http://localhost:8547/graphql"
	Addresses = ["0x1932c48b2bf8102ba33b4a6b545c32236e342f34"]
	rpcAddr =  "localhost:6666"
	rpcCorsList =  ["localhost"]
	rpcvHosts = ["localhost"]
