# This is sample config file for quorum reporting
title = "Quorum reporting confg example"
addresses = [
    { address = "0x1932c48b2bf8102ba33b4a6b545c32236e342f34", templateName = "SimpleStorage" }
]
templates = [
    { templateName = "SimpleStorage", abi = '[{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_initVal","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_value","type":"uint256"}],"name":"valueSet","type":"event"}]', storageLayout = '{"storage":[{"astId":3,"contract":"scripts/simplestorage.sol:SimpleStorage","label":"storedData","offset":0,"slot":"0","type":"t_uint256"}],"types":{"t_uint256":{"encoding":"inplace","label":"uint256","numberOfBytes":"32"}}}' }
]

[database]

    cacheSize = 10

[database.elasticsearch]

    urls = ["http://localhost:9200"]

[server]

    rpcAddr = "localhost:4000"
    rpcCorsList = ["*"]
    rpcvHosts = ["*"]
    uiPort = 3000

[connection]

    wsUrl = "ws://localhost:23000"
    graphQLUrl = "http://localhost:8547/graphql"
    reconnectInterval = 5
    maxReconnectTries = 5