# This is sample config file for quorum reporting
title = "Quorum reporting config example"

[reporting]

	wsUrl = "ws://localhost:10000"
	graphQLUrl = "http://localhost:11000/graphql"
	addresses = ["0x1932c48b2bf8102ba33b4a6b545c32236e342f34"]
	rpcAddr =  "localhost:20000"
	rpcCorsList =  ["localhost"]
	rpcvHosts = ["localhost"]
	reconnectInterval = 5
	maxReconnectTries = 5

