// user
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SELECT_CONTRACT = 'SELECT_CONTRACT';
export const GET_CONTRACTS = 'GET_CONTRACTS';

// system
export const CONNECT = 'CONNECT';
export const DISCONNECT = 'DISCONNECT';
export const UPDATE_ENDPOINT = 'UPDATE_ENDPOINT';
export const UPDATE_BLOCK_NUMBER = 'UPDATE_BLOCK_NUMBER';
export const UPDATE_ROWS_PER_PAGE = 'UPDATE_ROWS_PER_PAGE';
