on: [push, pull_request]
name: Tests
jobs:
  unit-tests:
    name: Unit testing in ${{ matrix.platform }} with go 1.13
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: go test ./...
